services:
  - type: web
    name: glassy-app
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/dist"
    routes:
      - source: "/login"
        destination: "/index.html"
        type: rewrite
      - source: "/register"
        destination: "/index.html"
        type: rewrite

      - source: "/app/*"
        destination: "/index.html"
        type: rewrite
      - source: "/*"
        destination: "/index.html"
        type: rewrite
